# Generated by Django 4.2.5 on 2023-09-20 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=255)),
                ('price', models.PositiveIntegerField()),
                ('availability', models.BooleanField(default=True)),
                ('creation_date', models.DateField()),
                ('description', models.TextField()),
            ],
        ),
    ]
